### ISSUE TITLE
Make it easier to give Feedback/Ask for help?

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#420]
Hi @kevincrepin, in our latest Monthly Meeting we talked about making it easier and more on the top of their mind for users to give us feedback when they are struggling to do what they want to do, or something bothers them about the UX. 

The conversation came about from the fact that it is part of the "Know Our Users" project strategy (that @ssin1901 is leading) to focus our attention on understanding unhappy users. 

We were wondering if we could therefore make this a bit more prominent on the Help Centre panel homepage - for example moving it higher up? Or if you have any other thoughts on how we could encourage people to communicate their pains to use more actively, ideas very welcome :) 

![image](https://user-images.githubusercontent.com/61320526/220597234-b01efc59-6364-46b5-8f52-4509c242d301.png)

Tagging @anettlinno and @ilmartyrk so they are in the loop too :)

**Comment by kevincrepin** [comment]
I think bringing it up into a separate section can work: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=586%3A21104&node-id=4801-41630&viewport=-14109%2C4595%2C1&scaling=min-zoom&starting-point-node-id=586%3A22466&show-proto-sidebar=1

**Comment by oksks** [comment]
@argoroots Can you please implement this? Thanks.

**Comment by BeccaMelhuish** [comment]
Do we need a mock-up of how it should look on the web version too? :)

**Comment by oksks** [comment]
I don't think we need a separate mockup in this case - it's just a matter of a small block redesign (which @argoroots can follow from Kevin's mockup) and bringing the block higher up, placing it between intro and search.

**Comment by oksks** [comment]
@devosama1, could you please implement this in the HC? Sorry to not mention it in the HC discussion earlier, forgot all about this request until now :/

**Comment by devosama1** [comment]
@oksks this is already inside the help centre which will render on the app as it is :)

**Comment by devosama1** [comment]
This task is complete

You can submit the forms inside these pages to receive email to info@citizenos.com which can further be forwarded to concerned team member. Also added a simply google captcha, the google captcha admin account is under osama@citizenos.com and currently there has been 10 verification so far in the panal. 

![image](https://github.com/citizenos/citizenos-web/assets/56334857/f046d76b-7e0e-4196-9047-e6404483d9e3)


Further enhancement suggestion @oksks @anettlinno : Basically i would like to add a keyword inside the email title, and you can add a forwarder in gmail so that anytime an email comes in for feedback and help that can be forwarded to that particular team member. Or a way to forward to slack (possible through zapier).

**Comment by BeccaMelhuish** [comment]
@oksks @devosama1 I see this marked as completed but I don't see the change: 

This is what Kevin's suggested re-design was (design linked by Kevin above)

![image](https://github.com/citizenos/citizenos-web/assets/61320526/7c73b9a5-fb64-4ee4-b8d6-b8d8acb8c872)

And this is how it is on the platform currently (at the bottom same as it always was)

![image](https://github.com/citizenos/citizenos-web/assets/61320526/43a21af8-56d7-4c2f-a6ce-a463247a9524)
