### ISSUE TITLE
BUG: News filter tabs not working correctly

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-web#482]
@devosama1 something's up with the news filters! 

When I click on any of the filter tabs that are not "All news", then go back to "All news" again, it doesn't change the articles that are shown, but keeps the filter of the previous tab I was on. 

For example, here (screenshot below) I had just clicked on "Case Studies". I went back to "All news", but the case studies are still what's shown. To get the correct "All news" articles to show, I have to refresh the page. 

(Using Chrome)

![image](https://github.com/citizenos/citizenos-web/assets/61320526/fabcae3c-d23a-48bb-8461-ed9356ecbb06)

**Comment by devosama1** [comment]
@BeccaMelhuish okay this is new!. could you add this as a TODO with new Indonesia team requirements. I have yet to receive those, and was gonna rebuild this a bit because we need to incorporate a way to distinguish Indonesia team news as well. So i guess this can be merged with that. 

@oksks any updates regarding Indonesia team requirements?

**Comment by BeccaMelhuish** [comment]
@devosama1 OK cool! I'm not involved in that but hopefully @oksks can add it :)

**Comment by oksks** [comment]
@devosama1 Hey hey, unfortunately Agustina's team is having a high workload due to YEP, so they haven't been able to deliver anything yet :( 
Can you maybe make the label already together with resolving this bug?
Please add the following articles to it, for starters:

https://citizenos.com/news/1200-citizens-attend-indonesia-opinion-festival-2022/
https://citizenos.com/news/our-new-government-partnership-for-youth-e-engagement-in-indonesia/
https://citizenos.com/news/interview-imam-gunawan-indonesian-ministry-of-youth-and-sport/

I think the label's name can safely be "Indonesia news" unless we think of something better, but this can probably be easily changed.

**Comment by devosama1** [comment]
The original all news/projects have been resolved.

**Comment by oksks** [comment]
Tested, works

**Comment by devosama1** [comment]
![image](https://github.com/citizenos/citizenos-web/assets/56334857/3613bf94-9577-4ef7-a47f-92f58c2deefe)
@oksks updated this as well as requested

**Comment by oksks** [comment]
Thank you!
