### ISSUE TITLE
Localisation - copy review

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-web#7]
**Overview**

Review the website content from localisation perspective.

**TODO**

- [ ] Review content
- [ ] Make a  bug/feature in GitHub for every shortcoming
- [ ] Once done, notify related parties in https://github.com/citizenos/citizenos-web/issues/6

**Comment by tiblu** [comment]
@oksks Created the task for you on the copy review

**Comment by tiblu** [comment]
@oksks Any progress on this?

**Comment by oksks** [comment]
> @oksks Any progress on this?
sorry, no, since to my knowledge Margo hasn't reviewed the web yet + his proposed changes haven't been implemented by himself or Liina + website bugs haven't been fixed yet = web isn't final from l10n perspective.

@tiblu pls can haz Github training? for a non-techie, it's really hard to orient and I don't know how to submit bugs or track stuff or see what I'm supposed to deliver.
